02 | 1-sort-strings, 2-pick, 3-omit (Task completed)
js-tasks-ru/js-20220513_evgeniy75 pull request #3
Opened 2022-05-18 17:29 UTC by evalekseev

2022-05-18 17:30 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-05-19 11:07 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +export function sortStrings(...props) {
зачем изменены аргументы функции?
в чем причина заменить `arr, param = 'asc'` на `...props`?

2022-05-19 11:07 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const [data, param = 'asc', ...other] = props;
почему `other` не используется?

2022-05-19 11:07 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const [data, param = 'asc', ...other] = props;
что такое `other`?

2022-05-19 11:08 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return sortDirection === 'asc' ? result : result.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-05-19 11:09 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    const searchKeys = (fields, obj) => {
c какой целью объявлена функция `searchKeys`?
можно ли логику из этой функции использовать в теле `pick`?

2022-05-19 11:10 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +        fields.forEach(fieldKey => {
цикл `forEach` тут явно лишний, от него следует избавиться

2022-05-19 11:10 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +export const pick = (...props) => {
почему заменены аргументы функции?

2022-05-19 11:11 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    const ignoreKeys = (fields, obj) => {
Проанализируйте решение `pick`, обратите внимание на замечания и схожим образом реализуйте `omit` функцию

2022-05-19 11:11 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-05-19 11:27 UTC, evalekseev commented on 02-javascript-data-types/1-sort-strings/index.js
> +export function sortStrings(...props) {
Думаю, что в данном случае это было лишнее, можно было оставить как есть, но вдруг магическим образом помимо arr и param прилетит еще куча всего ). Мне кажется так удобней, конечно мы можем потом все поймать через arguments, но такое решение мне видится более универсальным.

2022-05-19 14:20 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-05-20 13:08 UTC, dosandk approved these changes
good 👍

2022-05-20 13:08 UTC, merged